# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
    Record.destroy_all


    Record.create([{ species: "Atlantic Salmon",
                     weight: 24.30,
                     length: 35.0,
                     girth: 24.0,
                     date: DateTime.parse("15/07/1989 17:01"),
                     angler: "James McDonald",
                     waterbody: "Lake Ontario",
                     closestcommunity: "Toronto, ON",
                     lure: "Daredevil spoon",
                     latitude: 43.666667,
                     longitude: -79.416667,
                     imageurl: "http://www.ontariofishspecies.com/img5.jpg"
                   },
                   { species: "Aurora Trout",
                      weight: 6.64,
                      length: 22.3,
                      girth: 16.0,
                      date: DateTime.parse("01/08/1999 19:01"),
                      angler: "Luc Pilon",
                      waterbody: "Carol Lake",
                      closestcommunity: "Westree, ON",
                      lure: "#1 Silver Davis Hammer & Lil' Cleo",
                      latitude: 47.4187,
                      longitude: -81.5466,
                      imageurl: "http://www.registrelep-sararegistry.gc.ca/images/photos/spp065p1.jpg"
                    },
                    { species: "Black Crappie",
                      weight: 3.78,
                      length: 17.0,
                      girth: 16.5,
                      date: DateTime.parse("10/05/1986 21:01"),
                      angler: "Charles Sherrill",
                      waterbody: "Lake Erie",
                      closestcommunity: "Hillman Marsh, ON",
                      lure: "Minnow",
                      latitude: 42.0416,
                      longitude: -82.5138,
                      imageurl: "http://www.ontariofishspecies.com/imgC1.jpg"
                    },
                    { species: "Bluegill",
                      weight: 1.83,
                      length: 11.1,
                      girth: 13.5,
                      date: DateTime.parse("25/06/1995 21:01"),
                      angler: "Jason Hall",
                      waterbody: "Lake Erie",
                      closestcommunity: "St. Williams, ON",
                      lure: "Rapala Rattin' Rap",
                      latitude: 42.402,
                      longitude: -80.2454,
                      imageurl: "http://wdfw.wa.gov/fishing/washington/graphics/species/bluegill_DuaneRaver.jpg"
                    },
                    { species: "Bowfin",
                      weight: 15.10,
                      length: 31.5,
                      girth: 13.5,
                      date: DateTime.parse("27/06/2000 21:01"),
                      angler: "Mark Johnson",
                      waterbody: "Dog Lake",
                      closestcommunity: "Seeley’s Bay, On",
                      lure: "Live Bait",
                      latitude: 44.4773,
                      longitude:-76.2351,
                      imageurl: "http://www.ontariofishspecies.com/img4A.jpg"
                    },
                    { species: "Brook Trout",
                      weight: 14.5,
                      length: 31.5,
                      girth: 23.0,
                      date: DateTime.parse("01/06/1916 21:01"),
                      angler: "Dr. J. W. Cook",
                      waterbody: "Nipigon River",
                      closestcommunity: "Thunder Bay, ON",
                      lure: "n/a",
                      latitude: 48.3809,
                      longitude: -89.2477,
                      imageurl: "http://www.ontariofishspecies.com/imgF.jpg"
                    },
                    { species: "Brown Bullhead",
                      weight: 2.37,
                      length: 16.4,
                      girth: 9.3,
                      date: DateTime.parse("13/07/1989 21:01"),
                      angler: "Jeff Sereda",
                      waterbody: "401 Pond",
                      closestcommunity: "Ontario",
                      lure: "Worm",
                      latitude: 48,
                      longitude: -83,
                      imageurl: "http://www.ontariofishspecies.com/img13.jpg"
                    },
                    { species: "Brown Trout",
                      weight: 34.28,
                      length: 38.0,
                      girth: 28.0,
                      date: DateTime.parse("09/09/1994 21:01"),
                      angler: "Richard Matusiak",
                      waterbody: "Lake Ontario",
                      closestcommunity: "Mississauga, ON",
                      lure: "Little Cleo",
                      latitude: 43.5890452,
                      longitude: -79.6441198,
                      imageurl: "http://www.ontariofishspecies.com/img8.jpg"
                    },
                    { species: "Borbot (Ling)",
                      weight: 15.88,
                      length: 36.5,
                      girth: 21.0,
                      date: DateTime.parse("25/05/2015 21:01"),
                      angler: "Ernest Arpin",
                      waterbody: "Jessie Lake",
                      closestcommunity: "Nipigon, ON",
                      lure: "Smelt",
                      latitude: 49.0157351,
                      longitude: -88.26831600000003,
                      imageurl: "http://www.ontariofishspecies.com/img15.jpg"
                    },
                    { species: "Channel Catfish *NEW*",
                      weight: 33.36,
                      length: 39.3,
                      girth: 27.5,
                      date: DateTime.parse("13/07/1989 21:01"),
                      angler: "Gordon Kauffedlt",
                      waterbody: "Madawaska River",
                      closestcommunity: "Griffith, On",
                      lure: "Minnow and Jig",
                      latitude: 45.244097,
                      longitude: -77.166188,
                      imageurl: "http://www.ontariofishspecies.com/img1B.jpg"
                    },
                    { species: "Chinook Salmon",
                      weight: 46.38,
                      length: 47.0,
                      girth: 30.0,
                      date: DateTime.parse("07/08/2000 21:01"),
                      angler: "Harry Oosterveld",
                      waterbody: "Lake Ontario",
                      closestcommunity: "Oakville, ON",
                      lure: "Rac. Spoon",
                      latitude: 43.467517,
                      longitude: -79.6876659,
                      imageurl: "http://www.ontariofishspecies.com/img6.jpg"
                    },
                    { species: "Coho Salmon",
                      weight: 29.22,
                      length: 40.0,
                      girth: 24.3,
                      date: DateTime.parse("24/09/2013 21:01"),
                      angler: "Glen Hales",
                      waterbody: "Ganaraska River",
                      closestcommunity: "Port Hope, ON",
                      lure: "Fly - Crystal Egg Red",
                      latitude: 43.949164,
                      longitude: -78.293462,
                      imageurl: "http://www.ontariofishspecies.com/img7.jpg"
                    },
                    { species: "Common Carp",
                      weight: 39.88,
                      length: 1.0,
                      girth: 1.0,
                      date: DateTime.parse("23/01/2007 21:01"),
                      angler: "Matt Bird",
                      waterbody: "Lake Simcoe",
                      closestcommunity: "Gilford, ON",
                      lure: "Simcoe Bug/Minnow",
                      latitude: 44.225316,
                      longitude: -79.532308
                    },
                    { species: "Fallfish",
                      weight: 3.16,
                      length: 18.5,
                      girth: 13.0,
                      date: DateTime.parse("21/04/2012 21:01"),
                      angler: "Tony Baldasarra",
                      waterbody: "St. Lawrence River",
                      closestcommunity: "Ivey Lea, ON",
                      lure: "Liver",
                      latitude: 44.364853,
                      longitude: -76.01194,
                      imageurl: "http://www.ontariofishspecies.com/imgC.jpg"
                    },
                    { species: "Freshwater Drum",
                      weight: 21.53,
                      length: 35.0,
                      girth: 26.0,
                      date: DateTime.parse("25/10/2008 21:01"),
                      angler: "Mike Martin",
                      waterbody: "Bay of Quinte",
                      closestcommunity: "Picton, ON",
                      lure: "Dr. Death",
                      latitude: 44.007313,
                      longitude: -77.142369,
                      imageurl: "https://www.igfa.org/images/SpeciesID_Images/drum_freshwater.png"
                    },
                    { species: "Goldeye",
                      weight: 1.19,
                      length: 14.7,
                      girth: 9.0,
                      date: DateTime.parse("31/08/2003 21:01"),
                      angler: "Pamela Kerr",
                      waterbody: "Redstone River",
                      closestcommunity: "South Porcupine, ON",
                      lure: "Lure & Minnow",
                      latitude: 48.485359,
                      longitude: -81.210233,
                      imageurl: "https://tce-live2.s3.amazonaws.com/media/media/1f30454a-69e7-4977-b067-8b98b22b696d.jpg"
                    },
                    { species: "Lake Herring (Cisco)",
                      weight: 4.33,
                      length: 23.5,
                      girth: 12.7,
                      date: DateTime.parse("22/05/1991 21:01"),
                      angler: "Janice Binkley",
                      waterbody: "Corrine Lake",
                      closestcommunity: "Homepayne, ON",
                      lure: "Jig and Worm",
                      latitude: 49.212219,
                      longitude: -84.771444,
                      imageurl: "http://www.ontariofishspecies.com/imgE.jpg"
                    },
                    { species: "Lake Trout",
                      weight: 63.12,
                      length: 51.5,
                      girth: 32.8,
                      date: DateTime.parse("25/05/1952 21:01"),
                      angler: "Hubert Hammers",
                      waterbody: "Lake Superior",
                      closestcommunity: "Isle Royale, ON",
                      lure: "n/a",
                      latitude: 47.976258,
                      longitude: -88.931261,
                      imageurl: "http://www.ontariofishspecies.com/img99.jpg"
                    },
                    { species: "Lake Whitefish",
                      weight: 14.77,
                      length: 29.5,
                      girth: 19.8,
                      date: DateTime.parse("18/03/1996 21:01"),
                      angler: "Terry Frook",
                      waterbody: "Georgian Bay",
                      closestcommunity: "Wiarton, ON",
                      lure: "Mr. Champ Jig",
                      latitude: 44.741973,
                      longitude: -81.140834,
                      imageurl: "http://www.ontariofishspecies.com/img23.jpg"
                    },
                    { species: "Largemouth Bass",
                      weight: 10.43,
                      length: 22.0,
                      girth: 19.5,
                      date: DateTime.parse("26/08/1976 21:01"),
                      angler: "Mario Crysanthou",
                      waterbody: "Preston Lake",
                      closestcommunity: "Preston Lake, ON",
                      lure: "Jitterbug",
                      latitude: 43.980732,
                      longitude: -79.380126,
                      imageurl: "http://www.ontariofishspecies.com/img25.jpg"
                    },
                    { species: "Largenose Gar",
                      weight: 21.20,
                      length: 51.5,
                      girth: 20.0,
                      date: DateTime.parse("19/07/2014 21:01"),
                      angler: "Steven Grail",
                      waterbody: "Ottawa River",
                      closestcommunity: "Arnprior, ON",
                      lure: "Large Treble",
                      latitude: 45.434745,
                      longitude: -76.351847,
                      imageurl: "http://www.ontariofishspecies.com/img3.jpg"
                    },
                    { species: "Mooneye",
                      weight: 1.94,
                      length: 16.5,
                      girth: 11.5,
                      date: DateTime.parse("12/02/2013 21:01"),
                      angler: "Jack Therrien",
                      waterbody: "Ottawa River",
                      closestcommunity: "Constance Bay, ON",
                      lure: "Mr. Champ",
                      latitude: 45.486219,
                      longitude: -76.073418,
                      imageurl: "http://www.albertafishingguide.com/application/image/fish/lrg/mooneye.jpg"
                    },
                    { species: "Muskellunge",
                      weight: 65.0,
                      length: 58.0,
                      girth: 30.5,
                      date: DateTime.parse("16/10/1988 21:01"),
                      angler: "Kenneth O'Brien",
                      waterbody: "Lake Huron",
                      closestcommunity: "Blackstone Harbour, ON",
                      lure: "Rapala Countdown",
                      latitude: 45.159889,
                      longitude: -79.986014,
                      imageurl: "http://www.ontariofishspecies.com/img24.jpg"
                    },
                    { species: "Northern Pike",
                      weight: 42.12,
                      length: 1.1,
                      girth: 1.1,
                      date: DateTime.parse("14/07/1946 21:01"),
                      angler: "Harry Bell",
                      waterbody: "Delaney River",
                      closestcommunity: "Kenora, ON",
                      lure: "n/a",
                      latitude: 49.767042,
                      longitude: -94.489392,
                      imageurl: "http://www.ontariofishspecies.com/imgE1.jpg"
                    },
                    { species: "Pink Salmon",
                      weight: 13.06,
                      length: 32.7,
                      girth: 21.0,
                      date: DateTime.parse("23/09/1992 21:01"),
                      angler: "Ray Higaki",
                      waterbody: "St. Mary's River",
                      closestcommunity: "Sault Ste. Marie, ON",
                      lure: "Luhr Jensen Minnow",
                      latitude: 46.259249,
                      longitude: -84.165759,
                      imageurl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Pink_salmon_FWS.jpg/220px-Pink_salmon_FWS.jpg"
                    },
                    { species: "Pumpkinseed",
                      weight: 1.00,
                      length: 10.0,
                      girth: 14.0,
                      date: DateTime.parse("30/08/1997 21:01"),
                      angler: "Fred Thorn",
                      waterbody: "Beattie Lake",
                      closestcommunity: "Wiarton, ON",
                      lure: "Twister Tail & Jig & Frog",
                      latitude: 44.8304,
                      longitude: -81.264511,
                      imageurl: "http://www.ontariofishspecies.com/imgA.jpg"
                    },
                    { species: "Rainbow Smelt",
                      weight: 0.33,
                      length: 10.8,
                      girth: 5.5,
                      date: DateTime.parse("31/01/1993 21:01"),
                      angler: "Gerald Draper",
                      waterbody: "Lake Simcoe",
                      closestcommunity: "Sutton West, ON",
                      lure: "William's Junior",
                      latitude: 44.309378,
                      longitude: -79.360636,
                      imageurl: "http://www.bentzenlab.ca/wp-content/themes/pblabs/images/pb_pics/Gaspereausmelt1.jpg"
                    },
                    { species: "Rainbow Trout",
                      weight: 40.68,
                      length: 39.1,
                      girth: 29.4,
                      date: DateTime.parse("21/09/2005 21:01"),
                      angler: "Joanne Verdramin",
                      waterbody: "Lake Huron",
                      closestcommunity: "Little Current, ON",
                      lure: "AC Shiner",
                      latitude: 45.937406,
                      longitude: -81.792895,
                      imageurl: "http://www.ontariofishspecies.com/img9.jpg"
                    },
                    { species: "River Redhorse",
                      weight: 12.05,
                      length: 30.5,
                      girth: 19.3,
                      date: DateTime.parse("30/04/2007 21:01"),
                      angler: "Randy Walker",
                      waterbody: "Thames River",
                      closestcommunity: "Delaware, ON",
                      lure: "Silver Walleye Grub",
                      latitude: 42.909234,
                      longitude: -81.42009,
                      imageurl: "http://cdn2.arkive.org/media/EC/ECC11617-4DD3-48AD-8038-32AB60C0ED57/Presentation.Large/River-redhorse.jpg"
                    },
                    { species: "Rock Bass",
                      weight: 3.00,
                      length: 1.1,
                      girth: 1.0,
                      date: DateTime.parse("08/01/1974 21:01"),
                      angler: "Peter Gulin",
                      waterbody: "York River",
                      closestcommunity: "Delaware, ON",
                      lure: "n/a",
                      latitude: 42.909234,
                      longitude: -81.42009,
                      imageurl: "http://www.ontariofishspecies.com/img18.jpg"
                    },
                    { species: "Sauger",
                      weight: 4.40,
                      length: 22.2,
                      girth: 12.5,
                      date: DateTime.parse("07/11/1992 21:01"),
                      angler: "Kris Gagnier",
                      waterbody: "Detroit River",
                      closestcommunity: "Windsor, ON",
                      lure: "Black & Green Fuzzy Grub",
                      latitude: 42.191708,
                      longitude: -83.057591,
                      imageurl: "http://www.ontariofishspecies.com/imgC2.jpg"
                    },
                    { species: "Saugeye (Sauger x Walleye)",
                      weight: 4.53,
                      length: 22.5,
                      girth: 13.4,
                      date: DateTime.parse("21/10/1992 21:01"),
                      angler: "Philip Gaskell",
                      waterbody: "Lake of the Woods",
                      closestcommunity: "Horson, ON",
                      lure: "Vibrotail Jig",
                      latitude: 49.061,
                      longitude: -94.847543,
                      imageurl: "http://wildlife.ohiodnr.gov/portals/wildlife/images/fishing/saugeye.jpg"
                    },
                    { species: "Shorthead Redhorse",
                      weight: 5.55,
                      length: 24.0,
                      girth: 14.4,
                      date: DateTime.parse("04/05/1997 21:01"),
                      angler: "Steven Carter",
                      waterbody: "Trent River",
                      closestcommunity: "Trenton, ON",
                      lure: "Rapala Husky Jerk",
                      latitude: 44.101126,
                      longitude: -77.576313,
                      imageurl: "http://wildlife.ohiodnr.gov/Portals/wildlife/Species%20and%20Habitats/Species%20Guide%20Index/Images/shortheadredhorse.jpg"
                    },
                    { species: "Silver Redhorse",
                      weight: 8.81,
                      length: 27.0,
                      girth: 17.0,
                      date: DateTime.parse("23/05/1988 21:01"),
                      angler: "Bruce Johnstone",
                      waterbody: "North River",
                      closestcommunity: "Midland, ON",
                      lure: "White Plastic Grub",
                      latitude: 44.74951600000001,
                      longitude: -79.89219229999998,
                      imageurl: "http://roughfish.com/sites/default/files/styles/large/public/silver_redhorse1.jpg?itok=IgH95vvI"
                    },
                    { species: "Smallmouth Bass",
                      weight: 9.84,
                      length: 24.0,
                      girth: 18.3,
                      date: DateTime.parse("26/09/1954 21:01"),
                      angler: "Andy Anderson",
                      waterbody: "Birch Bark Lake",
                      closestcommunity: "Kinmount, ON",
                      lure: "n/a",
                      latitude: 44.799592,
                      longitude: -78.570856,
                      imageurl: "http://www.ontariofishspecies.com/imgE2.jpg"
                    },
                    { species: "Splake (F1 & Backcrosses *)",
                      weight: 20.71,
                      length: 35.0,
                      girth: 23.3,
                      date: DateTime.parse("17/05/1987 21:01"),
                      angler: "Paul Thompson",
                      waterbody: "Georgian Bay",
                      closestcommunity: "Wasaga Beach, ON",
                      lure: "Red Flourescent Rapala",
                      latitude: 44.5207419,
                      longitude: -80.0160668,
                      imageurl: "http://www.state.me.us/ifw/fishing/species/identification/images/splake.jpg"
                    },
                    { species: "Sunfish Hybrid",
                      weight: 1.04,
                      length: 11.0,
                      girth: 11.5,
                      date: DateTime.parse("24/07/1998 21:01"),
                      angler: "Jeff Buck",
                      waterbody: "Lake Huron",
                      closestcommunity: "Sagamok First Nation, On",
                      lure: "Mister Twister Jig & worm",
                      latitude: 46.128606,
                      longitude: -82.113801,
                      imageurl: "http://fisheries.tamu.edu/files/2013/10/HSF7-300x172.jpg"
                    },
                    { species: "Tiger Muskellunge",
                      weight: 26.44,
                      length: 49.0,
                      girth: 20.0,
                      date: DateTime.parse("07/10/2000 21:01"),
                      angler: "Ed Barbosa",
                      waterbody: "Georgian Bay, Moon River",
                      closestcommunity: "n/a",
                      lure: "n/a",
                      latitude: 45.122372,
                      longitude: -79.974218,
                      imageurl: "http://wdfw.wa.gov/fishing/washington/graphics/species/tiger_muskie_TimKnepp.jpg"
                    },
                    { species: "Walleye",
                      weight: 22.25,
                      length: 36.5,
                      girth: 21.0,
                      date: DateTime.parse("26/05/1943 21:01"),
                      angler: "Patrick Noon",
                      waterbody: "Niagara River",
                      closestcommunity: "Fort Erie, ON",
                      lure: "n/a",
                      latitude: 42.9017764,
                      longitude: -78.9721745,
                      imageurl: "http://www.ontariofishspecies.com/img21.jpg"
                    },
                    { species: "White Bass",
                      weight: 3.07,
                      length: 17.7,
                      girth: 14.4,
                      date: DateTime.parse("23/05/2009 21:01"),
                      angler: "Jin Zhang",
                      waterbody: "Sturgeon Falls",
                      closestcommunity: "Sturgeon Falls, ON",
                      lure: "Jig Spin and Gulp minnow",
                      latitude: 46.367948,
                      longitude: -79.92473,
                      imageurl: "http://www.ontariofishspecies.com/img20.jpg"
                    },
                    { species: "White Crappie",
                      weight: 2.71,
                      length: 15.4,
                      girth: 13.9,
                      date: DateTime.parse("08/01/2000 21:01"),
                      angler: "James Zahaluk",
                      waterbody: "Detroit River",
                      closestcommunity: "Amherstburg, ON",
                      lure: "Small Jig with Glow ball",
                      latitude: 42.1013779,
                      longitude: -83.1086977,
                      imageurl: "http://www.dnr.sc.gov/fish/species/assets/whitecrappielg.jpg"
                    },
                    { species: "White Perch",
                      weight: 1.5,
                      length: 1.0,
                      girth: 1.0,
                      date: DateTime.parse("01/01/1000 21:01"),
                      angler: "n/a",
                      waterbody: "n/a",
                      closestcommunity: "n/a",
                      lure: "n/a",
                      latitude: 51.253775,
                      longitude: -85.32321389999998,
                      imageurl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/White_Perch.jpg/250px-White_Perch.jpg"
                    },
                    { species: "White Sucker",
                      weight: 5.39,
                      length: 22.8,
                      girth: 13.3,
                      date: DateTime.parse("23/05/1996 21:01"),
                      angler: "Geoff Bernardo",
                      waterbody: "Lake Joseph",
                      closestcommunity: "Rosseau, ON",
                      lure: "Twister Tail Jig",
                      latitude: 45.262194,
                      longitude: -79.643592,
                      imageurl: "http://www.ontariofishspecies.com/img30.gif"
                    },
                    { species: "Wiper (Temperate Bass Hybrid)",
                      weight: 21.18,
                      length: 30.0,
                      girth: 25.0,
                      date: DateTime.parse("14/05/2000 21:01"),
                      angler: "Salvatore Oddo",
                      waterbody: "Detroit River",
                      closestcommunity: "Windsor, ON",
                      lure: "Lead Jig",
                      latitude: 42.3149367,
                      longitude: -83.0363633,
                      imageurl: "http://www.ontariofishes.ca/graphics/302.jpg"
                    },
                    { species: "Yellow Perch",
                      weight: 2.45,
                      length: 15.5,
                      girth: 12.0,
                      date: DateTime.parse("24/03/2010 21:01"),
                      angler: "Angelko Prepolec",
                      waterbody: "Lake St. Clair",
                      closestcommunity: "Windsor, ON",
                      lure: "Minnow",
                      latitude: 42.3149367,
                      longitude: -83.0363633,
                      imageurl: "http://www.ontariofishspecies.com/img1F.jpg"
                    },
                    { species: "American Eel (Historic/No entries accepted)",
                      weight: 5.1,
                      length: 38.5,
                      girth: 9.3,
                      date: DateTime.parse("30.07/2002 21:01"),
                      angler: "Kyle Richards",
                      waterbody: "Ottawa River",
                      closestcommunity: "Clarence, ON",
                      lure: "Minnow",
                      latitude: 45.564289,
                      longitude: -75.247726,
                      imageurl: "http://www.ohiohistorycentral.org/images/5/5c/American_Eel.jpg"
                    },
                    { species: "Lake Sturgeon (Historic/No entries accepted)",
                      weight: 168.0,
                      length: 69.0,
                      girth: 42.0,
                      date: DateTime.parse("29/05/1982 21:01"),
                      angler: "Edward Paszkowski",
                      waterbody: "Nottawasaga River",
                      closestcommunity: "Wasaga Beach, ON",
                      lure: "n/a",
                      latitude: 44.5207419,
                      longitude: -80.0160668,
                      imageurl: "http://www.ontariofishspecies.com/img1E.jpg"
                    }
                 ])
  p "Created new records from seeds"
